name: Testing and Code Quality

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage codeclimate-test-reporter

    - name: Run Pytest and Generate Coverage Report
      run: |
        pytest --cov=countdown_timer --cov-report=xml --cov-report=html

    - name: Upload Coverage to CodeClimate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        codeclimate-test-reporter format-coverage --input-type cobertura --output coverage/codeclimate.json
        codeclimate-test-reporter upload-coverage
